# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nbelpois <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/06/13 09:32:12 by nbelpois          #+#    #+#              #
#    Updated: 2018/06/13 12:29:08 by nbelpois         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_putchar.c ft_putstr.c open.c

all : $(NAME)

$(NAME) :
	    gcc -o $(NAME) $(SRC)

clean :
	    /bin/rm -f *.o

fclean : clean
	    /bin/rm -f $(NAME)
